language: java
install: true

jdk:
  - oraclejdk8

script:
  - ./gradlew build --scan -s

deploy:
  provider: releases
  api_key:
    secure: lty+YlfjEA++ikYOHOOUeRZWnQuZi+JB1ejuQn9dlfgquI7EexIt4U2rbTKwy25WMr3Mqlt058cYqluV0ZvibAfagkDZTxwP0V8zI7qIWIjRfqYSs46Y3pny2R8gPSPacruIFvBy6Y4cpB0GdJZWmW3Tt/UikTO40U0iy7XNIcCwowTfoBPr69Df5C5Ix5XfT0Iyfozgj58jbk+D85hFDMx4Lddn0+nXQglt8SbJM/5BLC2qtPunzy0dQBXkAoF7j5Q+Rl6WW4n6fRpFSG2b6wK37RwgENmNiQVtGLT/T7paSIO9bRJjRjJVh0S1q5oDonJaMPQQagzrnY1RwbiYox1CEhnfeMPpwDGYHtxYlenrPsqpx408azERTD042/N9Scghtva0IhHGxatPOScFb0Jjddx3v5Y8qwwpVLdmkcGlAa+2g+5vX7755Ze1bYZgmZHicicIlSymWzirlDHhEhQfSUMtcI/P9NMUmFrnl+nOaOeuyf3bnKyrRhHIxztx46wjeOjk0pFsjhJIgo3B1Z0YRSqsnvB1zY7h/R9O3zjSbxl8LKu4vg/W0WCv14HmxNo0S0myY2a6iHltFaJWzrec6dJHIrla2SyfeZ8or5MONqTnLIBFK83Q+Jq/gVYR9MIq8Uc1Eyjr5FajCxvap67ZsgRSfWizHVvk7N7SWjI=
  file:
    - "build/foundation-curriculum_DE_dev.pdf"
    - "build/foundation-curriculum_EN_dev.pdf"
  skip_cleanup: true
  draft: true
  overwrite: true
